### PR TITLE
Fixed duplicate class names in message

### PR DESCRIPTION
**Pull request by excelwebzone**
This is to solve a case when including for example multi mixins with the same message name:
```xml
    <mixins>
      <curie-major>gdbots:iam:mixin:create-user:v1</curie-major>
      <curie-major>acme:user:mixin:create-user:v1</curie-major>
    </mixins>
```

Resolve in:
```php
use Gdbots\Schemas\Iam\Mixin\CreateUser\CreateUserV1 as GdbotsIamCreateUserV1;
use Gdbots\Schemas\Iam\Mixin\CreateUser\CreateUserV1Mixin as GdbotsIamCreateUserV1Mixin;
use Gdbots\Schemas\Iam\Mixin\CreateUser\CreateUserV1Trait as GdbotsIamCreateUserV1Trait;

use Acme\Schemas\User\Mixin\CreateUser\CreateUserV1 as AcmeUserCreateUserV1;
use Acme\Schemas\User\Mixin\CreateUser\CreateUserV1Mixin as AcmeUserCreateUserV1Mixin;
use Acme\Schemas\User\Mixin\CreateUser\CreateUserV1Trait as AcmeUserCreateUserV1Trait;
```

### CODE REVIEW

**Comment by gdbrown** [comment]
ran a test of compiling gdbots/schemas with this and it produces an invalid message:

```php
<?php

namespace Gdbots\Schemas\Ncr\Request;

use Gdbots\Pbj\AbstractMessage;
use Gdbots\Pbj\FieldBuilder as Fb;
use Gdbots\Pbj\Schema;
use Gdbots\Pbj\Type as T;
use Gdbots\Schemas\Ncr\Mixin\GetNodeBatchRequest\GetNodeBatchRequestV1 as GdbotsNcrGetNodeBatchRequestV1;
use Gdbots\Schemas\Ncr\Mixin\GetNodeBatchRequest\GetNodeBatchRequestV1 as GdbotsNcrGetNodeBatchRequestV1Mixin;
use Gdbots\Schemas\Ncr\Mixin\GetNodeBatchRequest\GetNodeBatchRequestV1 as GdbotsNcrGetNodeBatchRequestV1Trait;
use Gdbots\Schemas\Pbjx\Mixin\Request\RequestV1;
use Gdbots\Schemas\Pbjx\Mixin\Request\RequestV1Mixin;
use Gdbots\Schemas\Pbjx\Mixin\Request\RequestV1Trait;

final class GetNodeBatchRequestV1 extends AbstractMessage implements
    GetNodeBatchRequest,
    RequestV1,
    GdbotsNcrGetNodeBatchRequestV1
  
{
    use RequestV1Trait;
    use GdbotsNcrGetNodeBatchRequestV1Trait;

    /**
     * @return Schema
     */
    protected static function defineSchema()
    {
        return new Schema('pbj:gdbots:ncr:request:get-node-batch-request:1-0-0', __CLASS__,
            [
                /*
                 * Context is a map of data that helps the NCR decide where to read/write data from.
                 * A common use case is multi-tenant applications.
                 */
                Fb::create('context', T\StringType::create())
                    ->asAMap()
                    ->pattern('^[\w\/\.:-]+$')
                    ->build()
            ],
            [
                RequestV1Mixin::create(), 
                GdbotsNcrGetNodeBatchRequestV1Mixin::create()
            ]
        );
    }
}

```

**Comment by gdbrown** [comment]
I am not getting a different set of issues with this PR.


```
..............................................PHP Fatal error:  Gdbots\Schemas\Ncr\Command\CreateEdgeV1 cannot use Gdbots\Schemas\Pbjx\Mixin\Command\CommandV1 - it is not a trait in /Users/greg/www/schemas/gdbots-schemas/src/php/Gdbots/Schemas/Ncr/Command/CreateEdgeV1.php on line 16

Fatal error: Gdbots\Schemas\Ncr\Command\CreateEdgeV1 cannot use Gdbots\Schemas\Pbjx\Mixin\Command\CommandV1 - it is not a trait in /Users/greg/www/schemas/gdbots-schemas/src/php/Gdbots/Schemas/Ncr/Command/CreateEdgeV1.php on line 16

```
if you download gdbots/schemas and use this PR and recompile, then look at the changes you'll see the issues.

**Comment by excelwebzone** [comment]
Working now.. 2 classes where changed:
```php
<?php

namespace Gdbots\Schemas\Ncr\Request;

use Gdbots\Pbj\AbstractMessage;
use Gdbots\Pbj\FieldBuilder as Fb;
use Gdbots\Pbj\Schema;
use Gdbots\Pbj\Type as T;
use Gdbots\Schemas\Ncr\Mixin\GetNodeBatchResponse\GetNodeBatchResponseV1 as GdbotsNcrGetNodeBatchResponseV1;
use Gdbots\Schemas\Ncr\Mixin\GetNodeBatchResponse\GetNodeBatchResponseV1Mixin as GdbotsNcrGetNodeBatchResponseV1Mixin;
use Gdbots\Schemas\Ncr\Mixin\GetNodeBatchResponse\GetNodeBatchResponseV1Trait as GdbotsNcrGetNodeBatchResponseV1Trait;
use Gdbots\Schemas\Pbjx\Mixin\Response\ResponseV1;
use Gdbots\Schemas\Pbjx\Mixin\Response\ResponseV1Mixin;
use Gdbots\Schemas\Pbjx\Mixin\Response\ResponseV1Trait;

final class GetNodeBatchResponseV1 extends AbstractMessage implements
    GetNodeBatchResponse,
    ResponseV1,
    GdbotsNcrGetNodeBatchResponseV1
  
{
    use ResponseV1Trait;
    use GdbotsNcrGetNodeBatchResponseV1Trait;

    /**
     * @return Schema
     */
    protected static function defineSchema()
    {
        return new Schema('pbj:gdbots:ncr:request:get-node-batch-response:1-0-0', __CLASS__,
            [],
            [
                ResponseV1Mixin::create(), 
                GdbotsNcrGetNodeBatchResponseV1Mixin::create()
            ]
        );
    }
}
```
```php
<?php

namespace Gdbots\Schemas\Ncr\Request;

use Gdbots\Pbj\AbstractMessage;
use Gdbots\Pbj\FieldBuilder as Fb;
use Gdbots\Pbj\Schema;
use Gdbots\Pbj\Type as T;
use Gdbots\Schemas\Ncr\Mixin\GetNodeBatchRequest\GetNodeBatchRequestV1 as GdbotsNcrGetNodeBatchRequestV1;
use Gdbots\Schemas\Ncr\Mixin\GetNodeBatchRequest\GetNodeBatchRequestV1Mixin as GdbotsNcrGetNodeBatchRequestV1Mixin;
use Gdbots\Schemas\Ncr\Mixin\GetNodeBatchRequest\GetNodeBatchRequestV1Trait as GdbotsNcrGetNodeBatchRequestV1Trait;
use Gdbots\Schemas\Pbjx\Mixin\Request\RequestV1;
use Gdbots\Schemas\Pbjx\Mixin\Request\RequestV1Mixin;
use Gdbots\Schemas\Pbjx\Mixin\Request\RequestV1Trait;

final class GetNodeBatchRequestV1 extends AbstractMessage implements
    GetNodeBatchRequest,
    RequestV1,
    GdbotsNcrGetNodeBatchRequestV1
  
{
    use RequestV1Trait;
    use GdbotsNcrGetNodeBatchRequestV1Trait;

    /**
     * @return Schema
     */
    protected static function defineSchema()
    {
        return new Schema('pbj:gdbots:ncr:request:get-node-batch-request:1-0-0', __CLASS__,
            [
                /*
                 * Context is a map of data that helps the NCR decide where to read/write data from.
                 * A common use case is multi-tenant applications.
                 */
                Fb::create('context', T\StringType::create())
                    ->asAMap()
                    ->pattern('^[\w\/\.:-]+$')
                    ->build()
            ],
            [
                RequestV1Mixin::create(), 
                GdbotsNcrGetNodeBatchRequestV1Mixin::create()
            ]
        );
    }
}
```

**Comment by gdbrown** [comment]
when compiled in gdbots/schemas the change does qualify the "use" statements for trait and mixin with a vendor prefix.  I think this is working as expected

**Review by gdbrown — CHANGES_REQUESTED** [review]
can you make the changelog a little more detailed.

**Review by gdbrown — APPROVED** [review]

**Pull request merged**
